### ISSUE TITLE
Update README or HowTO for customdata branch

### ISSUE THREAD

**Issue by tshrinivasan** [UYousafzai/easy_train_tesseract#1]
Thanks for the wonderful automation.

The font branch helped to build traindata for Tamil Language.
The README is excellent.

Update similar instructions for customdata branch too.

**Comment by UYousafzai** [comment]
hey tshrinivasan, I am glad that it was helpful, and I have been really busy recently whenever I find a small patch of time I'll make sure to update all the required instructions for the customdata branch as well. I will most likely do it over the weekend.

**Comment by tshrinivasan** [comment]
>
>
>
Sure. Thanks.

**Comment by tshrinivasan** [comment]
Sorry to trouble you. Just a request for followup.

**Comment by UYousafzai** [comment]
hey, no ofcourse not you're not bothering at all, I get super busy with my job often lose track of time, anyway I have updated the readme, also please make sure you read the Note at the end of the readme, super important, it might save you from wasting tons of hours, I am closing the issue however if you need any sort of help feel free to drop me an email.
Email: umaryousafzai9@gmail.com
