### ISSUE TITLE
Training other languages

### ISSUE THREAD

**Issue by davidb1** [UYousafzai/easy_train_tesseract#2]
On the `fonts` branch:
Training languages other than english - don't you have to go into every script and change `eng` to the language you wish to train? (this is missing from the README)

**Comment by UYousafzai** [comment]
Apologies, I think I missed that part and thank you for pointing it out, I went ahead and updated the ReadMe, however I feel like for future I'll write a small GUI that would give the users the ability to train tesseract with far much ease than to go through this trouble, you can go ahead and follow me to be updated about it if it drops on my github in the future.
