### ISSUE TITLE
LSTM Training: Can't encode transcription ERROR (for tam language)

### ISSUE THREAD

**Issue by Chaarangan** [UYousafzai/easy_train_tesseract#4]
I am getting the below error,

Can't encode transcription: 'வென்ற உயிரிழந்த .நீங்கள்‌ வர்றதுக்கு என்று கண்ணன்‌, நியாயமான இழக்கின்றனர்‌. தெரிந்துகொள்வோம்‌ ஐந்தாம்‌ சேலம்‌ சிறுகுடி' in language ''
Encoding of string failed! Failure bytes: ffffffe2 ffffff80 ffffff8c 20 ffffffe0 ffffffaf ffffffa8 20 ffffffe0 ffffffae ffffff92 ffffffe0 ffffffae ffffffa9 ffffffe0 ffffffaf ffffff8d ffffffe0 ffffffae ffffffb1 ffffffe0 ffffffae ffffffbe ffffffe0 ffffffae ffffff95 ffffffe0 ffffffaf ffffff81 ffffffe0 ffffffae ffffffae ffffffe0 ffffffaf ffffff8d ffffffe2 ffffff80 ffffff8c 2e 20 24 31 35
Can't encode transcription: 'பள்ளிவாசலில்‌ ௨ ஒன்றாகும்‌. $15' in language ''
Encoding of string failed! Failure bytes: ffffffe2 ffffff80 ffffff8c 20 ffffffe0 ffffffaf ffffffa8 ffffffe0 ffffffaf ffffffa6 ffffffe0 ffffffaf ffffffa7 ffffffe0 ffffffaf ffffffa7 20 ffffffe0 ffffffae ffffffa8 ffffffe0 ffffffae ffffffbf ffffffe0 ffffffae ffffffa9 ffffffe0 ffffffaf ffffff88 ffffffe0 ffffffae ffffffb5 ffffffe0 ffffffae ffffff9e ffffffe0 ffffffaf ffffff8d ffffffe0 ffffffae ffffff9a ffffffe0 ffffffae ffffffb2 ffffffe0 ffffffae ffffffbf ffffffe0 ffffffae ffffff95 ffffffe0 ffffffae ffffffb3 ffffffe0 ffffffaf ffffff8d ffffffe2 ffffff80 ffffff8c 20 ffffffe0 ffffffae ffffff85 32 24 ffffffe0 ffffffae ffffffaa 35 20 ffffffe0 ffffffae ffffff85 ffffffe0 ffffffae ffffffb4 ffffffe0 ffffffae ffffffbf ffffffe0 ffffffae ffffffa4 ffffffe0 ffffffaf ffffff8d ffffffe0 ffffffae ffffffa4 20 ffffffe0 ffffffae ffffff95 ffffffe0 ffffffaf ffffff81 ffffffe0 ffffffae ffffffae ffffffe0 ffffffaf ffffff8d ffffffe0 ffffffae ffffffaa ffffffe0 ffffffae ffffffbe ffffffe0 ffffffae ffffffaa ffffffe0 ffffffae ffffffbf ffffffe0 ffffffae ffffffb7 ffffffe0 ffffffaf ffffff87 ffffffe0 ffffffae ffffff95 ffffffe0 ffffffae ffffffae ffffffe0 ffffffaf ffffff8d ffffffe2 ffffff80 ffffff8c 20 ffffffe0 ffffffae ffffffaa ffffffe0 ffffffaf ffffff8b ffffffe0 ffffffae ffffffa4 ffffffe0 ffffffaf ffffff81 2c 20 ffffffe0 ffffffae ffffffaa ffffffe0 ffffffae ffffffb2 ffffffe0 ffffffaf ffffff8d ffffffe0 ffffffae ffffff95 ffffffe0 ffffffae ffffffb2 ffffffe0 ffffffaf ffffff88 ffffffe0 ffffffae ffffff95 ffffffe0 ffffffaf ffffff8d ffffffe0 ffffffae ffffff95 ffffffe0 ffffffae ffffffb4 ffffffe0 ffffffae ffffff95 ffffffe0 ffffffae ffffffae ffffffe0 ffffffaf ffffff8d ffffffe2 ffffff80 ffffff8c 20 ffffffe0 ffffffae ffffff86 ffffffe0 ffffffae ffffffa4 ffffffe0 ffffffaf ffffff8d ffffffe0 ffffffae ffffffa4 ffffffe0 ffffffae ffffffbf ffffffe0 ffffffae ffffffb0 ffffffe0 ffffffae ffffffae ffffffe0 ffffffaf ffffff82 ffffffe0 ffffffae ffffff9f ffffffe0 ffffffaf ffffff8d ffffffe0 ffffffae ffffff9f ffffffe0 ffffffaf ffffff81 ffffffe0 ffffffae ffffffae ffffffe0 ffffffaf ffffff8d ffffffe2 ffffff80 ffffff8c
........................................................................continue...

Check this and help to fix the issue.

Thanks.

**Comment by UYousafzai** [comment]
Please Follow the link given below, it highlights the root cause of the problem, please see if you're making one of the same mistakes, if you still need help, I'll keep the issue open for now.

Link: [1227](https://github.com/tesseract-ocr/tesseract/issues/1227)

**Comment by Chaarangan** [comment]
Thanks. Problem solved.
